### ISSUE TITLE
Question: Usage as storage chest

### ISSUE THREAD

**Issue by francoisdejgr** [nicolas-lang/Factorio.LongWarehouses#2]
Greetings

I like the mod.
Just a question : I use it as part of my factory, (storage) but I notice that if I set the filter and then blueprint the filter is not copied.
Is it something you are looking to add?
Here is an image of what I am doing, I can only do it because of your mod
![image](https://user-images.githubusercontent.com/17899999/128597961-118b645f-5e25-41fa-aee1-8282120830c5.png)

**Comment by nicolas-lang** [comment]
To be frank, I have not considered slot filters while designing the mod.
It is a meaningful addition and i will look into it - I'll post updates here about the progress.

**Tech Stuff**
The real issue is, that internally there exists three warehouses, one horizontal, one vertical and one that is only used in blueprints, and they get interchanged by the mod depending on the situation. While H/V are normal warehouses, the blueprint situation is a bit different to allow the rotation, and in fact it is not even a chest at that time.
It should be manageable using blueprint "tags" but I have never used them and it needs a bit of testing on my side.
A realistic time frame (if my life has no objections in the meantime) would be a test version within 2-3 month maybe a bit  faster depending on stuff ...

**Comment by nicolas-lang** [comment]
It should be more like 2-3 weeks, i was bored and already got a mostly working test version done... 
I just don't really have any time for the required testing and cleanup at the moment.

**Comment by nicolas-lang** [comment]
Prerelease-Testversion
https://github.com/nicolas-lang/Factorio.LongWarehouses/releases/tag/0.2.3-A

**Comment by nicolas-lang** [comment]
@francoisdejgr did you manage to check if the pre-release works for you ?

**Comment by nicolas-lang** [comment]
should be resolved by new release
